### PR TITLE
fix(web): update nice name

### LINKED ISSUE #188: Update name of population entry in webgui fails
If the name of an originally uploaded testcase in population view is changed, it works. However, if you change the name of a testcase that was not originally uploaded, it will not be changed.

### PR DESCRIPTION
**Pull request by jones718**
Fixed by:
Initialize empty nice name in controller in order to trigger insert function in viewTCsTempl.html

### CODE REVIEW

**Comment by TomSie** [comment]
Are you sure this works? Imho, the else will overwrite everything you set above! Am I missing something?

**Comment by jones718** [comment]
If there's no nice name, then no other name is needed. Therefore, an empty nice name is used to trigger the insert. I will make some more tests and maybe refactor the code to improve it.

**Comment by jones718** [comment]
I've come across an issue with the managed instances nice names. So merging is blocked until this is fixed.

**Review by TomSie — APPROVED** [review]

**Comment by TomSie** [comment]
This looks much better :) Thank you!

**Comment by p4cx** [comment]
It don't work as it should. Yes, I can rename "not-already-nice-named" testcases, but only in the view. After reloading the page and a glimpse into the database: no persistent new data/ no new nice name.

**Review by p4cx — APPROVED** [review]

**Pull request merged**
