### PR TITLE
Hexdump comp in webgui

### LINKED ISSUE #204: Information in web application: Diff between parent and this testcase
When selecting a testcase, give me a simple diff of the testcase and the parent(s).

### PR DESCRIPTION
**Pull request by p4cx**
image

### CODE REVIEW

**Comment by joyride9999** [comment]
Hi,
so leaving here my first observation:
I see this construct used often :  
` 
for row in rows:
            for num, x in enumerate(row):
                if num is 0:
                    testcaseHex = [x[i:i + 2] for i in range(0, len(x), 2)]
                elif num is 1:
                    pageCount = int(x/960) + (x % 960 > 0)
                elif num is 2:
                    parentID = x
                elif num is 3:
                    parentGUID = x
`

I think you can eliminate the second for as there is no particular reason to enumarate all the columns, i think you can access them directly.
Also for the first for , if you expect a single row to be returned for the sql query ... then again there should not be any need for a for loop.

**Comment by p4cx** [comment]
image

**Review by jones718 — COMMENTED** [review]
In hexdump.js line 153 the variable hexData is not used anymore and there should be no semicolon after curly braces if there's no statement.

**Comment by p4cx** [comment]
> semicolon after curly braces if there's no statement.

> If you’re an experienced JavaScript programmer, you may choose a no-semicolon code style like StandardJS. Otherwise, it’s best to use semicolons to avoid possible pitfalls. The majority of developers put semicolons.
[https://javascript.info/coding-style#semicolons](https://javascript.info/coding-style#semicolons)

I will remove the unused variable, but won't "fix" the semicolons. They do not affect the readability of the code.

**Review by jones718 — APPROVED** [review]

**Comment by jones718** [comment]
While working on the next feature, I've realized that the id="offset" in viewTCsTempl.html is not unique. Maybe loop.index could be used here as well.

**Comment by p4cx** [comment]
> While working on the next feature, I've realized that the id="offset" in viewTCsTempl.html is not unique. Maybe loop.index could be used here as well.

It's now unique, thanks for the comment :)

**Pull request merged**
